add optional checksum checking to fetch-url

diff --git a/fetch-url b/fetch-url
--- a/fetch-url
+++ b/fetch-url
@@ -26,9 +26,18 @@ done
 
 url="$1"
 dst="$2"
+checksum="$3" # optional parameter
 
 proto=${url%%://*}
 
 . /usr/lib/fetch-url/$proto
 
-protocol_fetch "$url" "$dst"
+protocol_fetch "$url" "$dst" || exit $?
+
+if [ "$checksum" ]; then
+	filesum=$(md5sum $dst | cut -d' ' -f1)
+	if [ "$filesum" != "$checksum" ]; then
+		echo "ERROR: checksum mismatch on '$url' (sum is '$filesum', rather than the expected '$checksum')" >&2
+		exit 2
+	fi
+fi
